name: connectorph
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^1.0.4
  image_picker: ^0.6.0+17
  tflite: ^1.0.5
  firebase_storage: ^4.0.0
  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  modal_progress_hud: ^0.1.3
  carousel_slider: ^2.3.1
  geolocator: ^6.0.0
  geocoder: ^0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Architects
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-LightItalic.ttf
  assets:
    - images/
    - assets/labels.txt
    - assets/model_unquant.tflite